sudo: required
before_install:
  # Install latest version docker CE
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker version
  # Install latest version of docker-compose
  - sudo apt-get install -y python-pip && pip install --upgrade pip
  - sudo pip install docker-compose
  - docker-compose version
services:
  - docker

script:
  - docker build --rm --no-cache --tag quay.io/shazchaudhry/docker-jenkins .
  - docker images
  - docker inspect quay.io/shazchaudhry/docker-jenkins
  - docker run -d --rm --name jenkins --publish 8080:8080 --volume jenkins_home:/var/jenkins_home --volume /var/run/docker.sock:/var/run/docker.sock quay.io/shazchaudhry/docker-jenkins
  - docker ps -a
  - docker stop jenkins
  - docker login -u="shazchaudhry" -p=${QUAY_PASSWORD} quay.io
  - docker push quay.io/shazchaudhry/docker-jenkins
