sudo: required
before_install:
  # Install latest version docker CE
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  # Install latest version of docker-compose
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq python-pip && pip install --upgrade pip
  #- sudo pip install docker-compose
  #- docker-compose version

services:
  - docker

before_script:
  - docker build --rm --no-cache --tag quay.io/shazchaudhry/docker-jenkins .
  - docker image ls

script:
  - echo "admin" | docker secret create jenkins-user -
  - echo "admin" | docker secret create jenkins-pass -
  - docker stack deploy -c docker-compose.yml jenkins
  - sleep 60 #wait for jenkins to come up
  - docker ps -a
  - docker stack services jenkins
  - docker volume inspect jenkins_home

after_script:
  - docker login -u="shazchaudhry" -p=${QUAY_PASSWORD} quay.io
  - docker push quay.io/shazchaudhry/docker-jenkins:latest
