version: "3.3"

services:

  jenkins:
    image: quay.io/shazchaudhry/docker-jenkins
#    hostname: jenkins
#    environment:
#      - JENKINS_OPTS='--prefix=/jenkins'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - jenkins_home:/var/jenkins_home
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

#volumes:
#  jenkins_home:
