version: "3.4"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  jenkins:
    image: quay.io/shazchaudhry/docker-jenkins:latest
    user: root
    environment:
      - JENKINS_OPTS='--prefix=/jenkins'
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    secrets: # See how secrets are used in this jenkins image at: https://github.com/shazChaudhry/docker-jenkins/blob/master/config/security.groovy
      - jenkins-user
      - jenkins-pass
    deploy:
      labels:
        - com.df.port=8080
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins

secrets:
  jenkins-pass:
    external: true
  jenkins-user:
    external: true

volumes:
  jenkins_home:

networks:
  proxy:
